name: Tracebit Configure Credentials
description: Tracebit Configure AWS Credentials

inputs:
  customer-id:
    description: "Customer ID"
    required: false
    default: "community"

  api-host:
    description: "Domain name where the API is hosted"
    required: false

  api-token:
    description: "API token used to authenticate with the API"
    required: true

  profile:
    description: "AWS profile"
    required: true

  profile-region:
    description: "AWS region for the profile"
    required: true

  async:
    description: "Run the action in the background without making the other steps wait for it to finish."
    required: false

outputs:
  aws-access-key-id:
    description: "The AWS access key ID"
  aws-secret-access-key:
    description: "The AWS secret access key"
  aws-session-token:
    description: "The AWS session token"
  profile-name:
    description: "The name of the AWS profile"

runs:
  using: "node24"
  pre: "dist/pre.js"
  main: "dist/index.js"
