name: Example

on:
  push:

env:
  allow_showing_creds_in_test_repo: ${{ github.repository != 'tracebit-com/tracebit-community-action' }}

jobs:
  issue-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure credentials
        continue-on-error: true
        uses: tracebit-com/tracebit-community-action@517c410eae144100a1995cd720094c010995994d
        with:
          customer-id: ${{ vars.SECURITY_CUSTOMER_ID }}
          api-token: ${{ secrets.SECURITY_API_TOKEN }}
          profile: administrator
          profile-region: us-east-1
          async: true

      - name: Show env
        if: ${{ env.allow_showing_creds_in_test_repo == 'true' }}
        run: printenv

      - name: Show aws config
        run: |
          cat ~/.aws/config
          cat ~/.aws/credentials

      - name: Show ssh config
        run: |
          cat ~/.ssh/config 2>/dev/null || echo "(no ssh config)"
          echo "---"
          ls -la ~/.ssh/prod_deploy ~/.ssh/prod_deploy.pub 2>/dev/null || echo "(no ssh keys)"
