name: Sync to Public Repository

on:
  push:
    branches:
      - main
    tags:
      - "*"

permissions:
  contents: read # Needs to read the repo to simulate what actual usage is

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  sync:
    name: Push to public repository
    # Only run in the internal repository, not in the public one, and only for main or tags
    if: github.repository != 'tracebit-com/tracebit-community-action' && (github.ref == 'refs/heads/main' || github.ref_type == 'tag')
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0 # Full history needed for pushing
          fetch-tags: true
          persist-credentials: false # Don't persist the default GITHUB_TOKEN

      - name: Configure credentials
        uses: tracebit-com/tracebit-community-action@904ee3a84578e3b19bcd0e8c9354051fe148d51e # v1.3.0
        with:
          customer-id: ${{ vars.SECURITY_CUSTOMER_ID }}
          api-token: ${{ secrets.SECURITY_API_TOKEN }}
          profile: administrator
          profile-region: us-east-1
          async: true

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add public repository as remote
        env:
          PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          git remote add public https://x-access-token:${PUBLIC_REPO_TOKEN}@github.com/tracebit-com/tracebit-community-action.git

      - name: Push to public repository
        run: |
          git push public ${GITHUB_REF}
